FROM node:22

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --ignore-scripts

COPY . .

RUN apt-get update && apt-get install -y postgresql-client

RUN npx prisma generate

COPY entrypoint.sh . 
RUN chmod +x entrypoint.sh

EXPOSE 5000

ENTRYPOINT ["/app/entrypoint.sh"]