# Étape 1 : build
FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma
RUN npm ci --no-audit --no-fund

COPY . .
RUN npm run build
RUN npm prune --omit=dev

# Étape 2 : image finale
FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=preprod

# Copier uniquement le résultat du build et les fichiers nécessaires
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./

EXPOSE 5000
CMD ["node", "dist/app/server.js"]
